name: Scrape and Save HTML

on:
  schedule:
    # 每隔一小时运行一次
    - cron: "0 * * * *" # 使用 UTC 时间，格式为 cron 表达式

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 使用 curl 获取 HTML 内容
    - name: Fetch HTML content
      run: curl -s https://m.libahao.com/xiaoshuodaquan/page_204.html -o tt.html

    # 将文件提交到仓库
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add tt.html
        git commit -m "Update tt.html with fetched HTML content"
        git push
